newtab: revv up to also manage terminal emulator start up

diff --git a/bin/newtab b/bin/newtab
--- a/bin/newtab
+++ b/bin/newtab
@@ -1,12 +1,54 @@
 #!/bin/sh
-# i use both i3 and tmux like tabbed multiplexers, this launches a
-# command in a new 'tab'. This is mostly used by xdg-open.
-# Example: newtab watch lsof -i -n -P
-if [ -n "$TMUX" ]; then
-  tmux new-window "$@"
-elif [ -n "$DISPLAY" ]; then
-  i3-sensible-terminal -e "$@" &
-else
-  echo "No multiplexer found"
-  exit 1
+# i use both i3 and tmux like tabbed multiplexers, this launches a new 'tab'.
+# This is mostly used by xdg-open.
+# Option -t: requires stdio connected to a terminal
+
+fail() {
+	echo "$1" >&2
+	exit 1
+}
+
+cmd_exists() {
+	command -v "$1" >/dev/null 2>&1
+}
+
+xorg=1
+
+while test -n "$1"; do
+	case "$1" in
+	(-t)	unset xorg
+		shift
+		;;
+	(-*)	fail "Invalid option $1";;
+	(*)	break;;
+	esac
+done
+
+# default to user shell in a terminal
+if ! test -n "$1"; then
+	set -- "$SHELL"
+	unset xorg
 fi
+
+# gui programs in xorg get spawned normally
+if test -n "$xorg"; then
+	setsid "$@" &
+elif test -n "$TMUX"; then
+	tmux new-window "$@"
+elif test -n "$DISPLAY" && cmd_exists urxvtd; then
+	export RXVT_SOCKET="${XDG_RUNTIME_DIR}/rxvt${DISPLAY}.sck"
+	if ! urxvtc -e "$@"; then
+		urxvtd -q -f -o
+		urxvtc -e "$@"
+	fi
+elif test -n "$DISPLAY" && cmd_exists urxvt; then
+	setsid urxvt -e "$@" &
+elif test -n "$DISPLAY" && cmd_exists xterm; then
+	setsid xterm -e "$@" &
+elif test -n "$DISPLAY" && cmd_exists i3-sensible-terminal; then
+	setsid i3-sensible-terminal -e "$@" &
+else
+	fail "No multiplexer found"
+fi
+
+sleep 1
